apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: giovane1999/hello-go:latest
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 2
            failureThreshold: 10
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 2
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          resources:
            requests:
              cpu: "100m"
              memory: "20Mi"
            limits:
              cpu: "200m"
              memory: "40Mi"
